### ISSUE TITLE
Problem with subtract when a geometry is offset (translate(...))

### ISSUE THREAD

**Issue by ljaureguil** [chandlerprall/ThreeCSG#44]
I made some threejs models using your ThreeCSG like 4 months ago and now replace ThreeCSG with the new update and seems to be a bug with the geometry generated... check the pictures

... Same codes results after Update

![screenshot_2018-08-28-21-41-35](https://user-images.githubusercontent.com/33967760/44766011-39a6f380-ab0c-11e8-8159-761ac09e29b5.png)

...Same codes with Original version

![screenshot_2018-08-28-21-39-27](https://user-images.githubusercontent.com/33967760/44766023-4a576980-ab0c-11e8-8416-6e1a30470da7.png)

**Comment by Irrelon** [comment]
Did you ever work out what was causing this?
